### ISSUE TITLE
node.microformats.io down

### ISSUE THREAD

**Issue by gRegorLove** [microformats/microformats.io#18]

**Comment by veganstraightedge** [comment]
I think it's because @glennjones' site's SSL/HTTPS isn't working at the moment.

node.microformats.io was a redirect to https://glennjones.net/tools/microformats/ which is down.

I'll look into getting https://github.com/glennjones/microformat-node deployed to heroku directly with auto deploys for new commits.

**Comment by gRegorLove** [comment]
I think @jalcine is looking into getting this back up.

**Comment by jalcine** [comment]
Should be up no later than this Friday

(Originally published at: https://jacky.wtf/2022/7/a0is)

**Comment by gRegorLove** [comment]
Looks like this is back up, thanks @jalcine! 🎉
